name: Build and Upload CactusROM Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Upload Files to SourceForge
        run: |
          # Install SSH client
          sudo apt-get install -y openssh-client

          # Define SourceForge details
          SOURCEFORGE_USER="spoinkoscdn"
          SOURCEFORGE_PROJECT="cactusrom"
          SOURCEFORGE_HOST="web.sourceforge.net"
          SOURCEFORGE_PATH="/home/project-web/cactusrom/htdoc/"

            # Upload the image to SourceForge using rsync
            rsync -avz -e "sshpass -p $SOURCEFORGE_PASSWORD ssh -o StrictHostKeyChecking=accept-new" "index.html" "$SOURCEFORGE_USER@$SOURCEFORGE_HOST:$SOURCEFORGE_PATH/"
            echo [Done!]
          done
        env:
          SOURCEFORGE_PASSWORD: ${{ secrets.SOURCEFORGE_PASSWORD }}
